# Generated by Django 4.0.5 on 2022-06-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fyp_backend_app.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.ManyToManyField(blank=True, to='fyp_backend_app.request'),
        ),
    ]
