# Generated by Django 4.0.5 on 2022-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_backend_app', '0002_alter_student_project_alter_student_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.ManyToManyField(blank=True, null=True, to='fyp_backend_app.request'),
        ),
    ]
