# Generated by Django 4.0.5 on 2022-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_backend_app', '0005_alter_project_id_alter_project_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='request',
            field=models.ManyToManyField(blank=True, to='fyp_backend_app.request'),
        ),
    ]
