# Generated by Django 4.0.5 on 2022-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_backend_app', '0006_alter_student_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_grade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'Proposal Submitted'), (2, 'Proposal Approved'), (3, 'D1 submitted'), (4, 'D1 approved'), (5, 'D2 submitted'), (6, 'D2 approved'), (7, 'R1 submitted'), (8, 'R1 approved'), (9, 'R2 submitted'), (10, 'R2 approved'), (11, 'Final Project Submitted'), (12, 'Final Project Approved')], default=0),
        ),
    ]
