# Generated by Django 4.0.5 on 2022-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_backend_app', '0007_project_total_grade_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
