const SupervisorsIds=[
    {
        key:1,
        id:"amateen12",
        pass:"abcsdf"
    },
    {
        key:2,
        id:"umairbabar1",
        pass:"abcsdf"
    },
    {
        key:3,
        id:"shahidfarid22",
        pass:"abcsdf"
    },
    {
        key:4,
        id:"wasim23",
        pass:"abcsdf"
    },
    {
        key:5,
        id:"eshaaftab111",
        pass:"abcsdf"
    },
    {
        key:6,
        id:"shahzad34",
        pass:"abcsdf"
    },
    {
        key:7,
        id:"tariq87",
        pass:"abcsdf"
    },
    {
        key:8,
        id:"abdullah",
        pass:"abcsdf"
    }
    ]
    export default SupervisorsIds;